name: Sampath Rates Tracker

on:
  schedule:
    - cron: "0 */3 * * *"   # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python sampath_rates.py

      - name: Commit CSV if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add latest_rates.csv
          git commit -m "Update CSV [skip ci]" || echo "no changes to commit"
          git push
